### PR TITLE
Add support for Apple Watch Series 7

### PR DESCRIPTION
**Pull request by DanTheMann15**

### CODE REVIEW

**Comment by nikias** [comment]
Yes I was about to add them as well but then realized they are not even available for purchase yet. But I guess it can't hurt to have it ready for when they arrive.

**Comment by DanTheMann15** [comment]
there really is no reason to wait. 

and tsschecker is also being updated too, i've already added full support for them into my fork.

**Comment by nikias** [comment]
Could you use your proper github email address for your commits? I hate having the `*users.noreply.github.com` in the commit log.

**Comment by DanTheMann15** [comment]
it should be good now.

**Comment by nikias** [comment]
Ok I got your email, but you should switch your email address to non-visible on your github profile. Merged it with commit 0165076dedcad80c9a6886424cdc0992a88ce2ae.

**Pull request closed without merging**
