### PR TITLE
Patches to enable building libirecovery without libusb on OS X.

### PR DESCRIPTION
**Pull request by aburgh**
I don't have much experience with autoconf, so please review my changes to configure.ac. And, I do not have an installation of Linux, so please confirm that it builds.

On Nov 14th, I sent an email to the list with the subject "libirecovery without libusb on OS X" suggesting a cleaner way to write the conditional directives, which may be worth considering.

### CODE REVIEW

**Comment by nikias** [comment]
@aburgh any idea what might be wrong with El Capitan? In particular usb bulk transfers don't seem to work. This (from iokit_usb_bulk_transfer):

```
result = (*intf)->WritePipeTO(intf, pipeRef, data, size, timeout, timeout);
```

returns 0xe0004051 which means USB timeout.

Any idea what might be wrong?

**Comment by aburgh** [comment]
No ideas yet. I want to double-check that the configuration and interfaces are set up appropriately. I recall that the libusb implementation had some redundant or unnecessary calls that I didn't duplicate exactly in the iokit* version.

I'm on Apple's USB mailing list and I don't see any relevant emails there at first glance. I want to try reproducing the problem, but I don't have `idevicerestore

**Comment by nikias** [comment]
Recovery mode. I didn't try DFU mode, but that's using control transfers anyway.

**Comment by nikias** [comment]
libusb has the same issue btw.

**Comment by nikias** [comment]
FYI: I just by accident found out that it works with libusb when I remove the call ```libusb_set_interface_alt_setting(client->handle, usb_interface, usb_alt_interface)```

**Comment by nikias** [comment]
I fixed it. Merged with some changes and enabled IOKit by default.

**Comment by aburgh** [comment]
Thanks. I merged the update into my fork, too.

**Pull request closed without merging**
