### PR TITLE
Display device's product id and name when querying device info

### PR DESCRIPTION
**Pull request by ethanatwork**
**Example of new output:**
$ irecovery -q
Name: Mac mini (M1, 2020)
Type: Macmini9,1
CPID: 0x8103
CPRV: 0x11
BDID: 0x22
ECID: 0xxxxxxxxxxxxxxxxx
CPFM: 0x03
SCEP: 0x01
IBFL: 0x3c
SRTG: iBoot-5540.0.0.400.2
SRNM: N/A
IMEI: N/A
NONC: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
SNON: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
MODE: DFU

### CODE REVIEW

**Comment by DanTheMann15** [comment]
you can also add support for printing the device's motherboard as well by inserting this line:

`printf("BORD: %s\n", modelinfo->hardware_model);`

**Comment by ethanatwork** [comment]
@DanTheMann15 Thanks for the tip! I added that in.  Any chance you could review my code for me?
Thanks,
Ethan

**Comment by DanTheMann15** [comment]
see my test branch in my repo here for the proper implementation: https://github.com/DanTheMann15/libirecovery/tree/test

copy the changed code and stick it into your repository.

**Comment by nikias** [comment]
This was recently added in a slightly different way.

**Pull request closed without merging**
