### PR TITLE
support new devices (Spring 2021)

### PR DESCRIPTION
**Pull request by DanTheMann15**
adds support for:
* iPad Pro (M1, 2021) models
* iMac (M1, 2021) models
* Apple TV 4K (2nd generation)

Other Changes:
* differentiate iPad Pro generations, except for the 10.5 and 9.7 inch models.

### CODE REVIEW

**Comment by nikias** [comment]
Hey I already added the devices myself, except for AppleTV 4k 2nd gen, where did you find chipid/boardid values?

**Comment by DanTheMann15** [comment]
> Hey I already added the devices myself, except for AppleTV 4k 2nd gen, where did you find chipid/boardid values?

straight from the BuildManifest.plist inside the fat OTA found here: https://www.theiphonewiki.com/wiki/OTA_Updates/Apple_TV/14.5#Apple_TV_4K_.282nd_generation.29

other device info is from the DeviceTree.

**Comment by nikias** [comment]
Ok great, I didn't check the OTA ones, I kinda suspected it was from there, was just curious since ipsw.me doesn't have that device.

**Comment by nikias** [comment]
Will add it.

**Pull request closed without merging**
