### PR TITLE
Add MacBook Pro 2020 13" four thunderbolt

### PR DESCRIPTION
**Pull request by MrBenFTW**
Add MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

**IMPORTANT**: I don't know how to get those hex values, so I have put `??` in their place. Please tell me how I get them so I can add it for you. Terminal output: [Imgur](https://imgur.com/a/KY769pA)

if you need help, DM me on twitter. ([A_MrBenMitchell](https://twitter.com/A_MrBenMitchell))

### CODE REVIEW

**Comment by nikias** [comment]
https://ipsw.me/iBridge2,16/info has the values :)

**Comment by nikias** [comment]
Oh but now j214kap doesn't match....

**Comment by MrBenFTW** [comment]
> https://ipsw.me/iBridge2,16/info has the values :)

Board config doesn't match up.

ipsw.me : `j140aap`

My MacBook: `j214kap`

**Comment by nikias** [comment]
We need to figure out which one is correct, in any case I can't accept a pull request with `??` in it.

**Comment by MrBenFTW** [comment]
Yep understandable, if you can tell me the command I can run it to find out.

Is it one of these?
```
# ECID in decimal instead of Hex
/usr/libexec/remotectl get-property localbridge UniqueChipID
# Chip ID CPID in decimal (32786 == 0x8012)
/usr/libexec/remotectl get-property localbridge ChipID
# Board Revision CPRV in decimal instead of hex
/usr/libexec/remotectl get-property localbridge BoardRevision
# Board ID (BDID) in decimal instead of hex
/usr/libexec/remotectl get-property localbridge BoardId
# Hardware Model is the name of the Board
/usr/libexec/remotectl get-property localbridge HWModel
```

**Comment by MrBenFTW** [comment]
`BDID` is 62 and CPID remains unchanged 32786

**Comment by nikias** [comment]
Yes, `HWModel` is what we need.

**Comment by MrBenFTW** [comment]
> Yes, `HWModel` is what we need.

J214kAP

**Comment by MrBenFTW** [comment]
image

**Comment by nikias** [comment]
```{ "iBridge2,16", "j214kap",  0x3E, 0x8012, "Apple T2 MacBookPro16,2 (j214k)" },```

**Comment by MrBenFTW** [comment]
Where does `j214k ` come from?

**Comment by nikias** [comment]
Well it's just `j214kap` without the `ap`.

**Comment by MrBenFTW** [comment]
Ah okay, for future reference I have made a quick script to get everything and output it like so: 
image

[Script (github)](https://gist.github.com/MrBenFTW/2d1d581d149873dea45bbbe25e3f37a4)

**Comment by nikias** [comment]
Alright. Let me talk to the ipsw.me guy to see where he got those values from and have him fix them.

**Comment by DanTheMann15** [comment]
i added more T2 Devices in #77

**Pull request closed without merging**
